### ISSUE TITLE
`warning` and `primary` SharedButton's look quite similar.

### ISSUE THREAD

**Issue by 0xDaedalus** [tallyhowallet/extension#1115]
Here is an example of the same button with different `type`'s.

Warning:
<img width="226" alt="image" src="https://user-images.githubusercontent.com/94649004/157135435-cdbfec4d-db54-4c47-a46c-a08cd9e54c84.png">

Primary:
<img width="228" alt="image" src="https://user-images.githubusercontent.com/94649004/157135412-3db9856d-db63-4d07-8c81-6cd0ba8510c5.png">

I am by no means a designer but just wanted to flag that I had trouble distinguishing them while developing.  What do you guys think?

**Comment by VladUXUI** [comment]
Agreed, that is why we rarely(if at all) use the warning button.
The two colours are quite similar and that becomes a bit more evident when they need to be used one next to another.

It's a bit tricky because of our main colour, but i'm open to suggestion on what other colour we can use instead of Yellow.

**Comment by 0xDaedalus** [comment]
Closed b/c stale
