### ISSUE TITLE
Consistently use `type` instead of `interface` across the codebase.

### ISSUE THREAD

**Issue by 0xDaedalus** [tallyhowallet/extension#1120]
We have made the switch everywhere except for React components and we should get to a point where we are consistent across the codebase.

For Example: [`interface Props` should be changed to `type Props = `](https://github.com/tallycash/extension/blob/main/ui/components/Shared/SharedFeeSelectButton.tsx#L4)

**Comment by cairomassimo** [comment]
I'm personally for `interface` over `type`, but in either case we should be consistent. Let's configure https://typescript-eslint.io/rules/consistent-type-definitions/ either way, and then we should just follow the linter. It's an auto-fixable rule BTW

**Comment by beemeeupnow** [comment]
After reading this: https://www.typescriptlang.org/docs/handbook/2/everyday-types.html#differences-between-type-aliases-and-interfaces

I'm convinced to generally prefer `interface` as well for many things.

Copied this snippet in case the source ever goes away:

> * Prior to TypeScript version 4.2, type alias names [may appear in error messages](https://www.typescriptlang.org/play?#code/PTAEGEHsFsAcEsA2BTATqNrLusgzngIYDm+oA7koqIYuYQJ56gCueyoAUCKAC4AWHAHaFcoSADMaQ0PCG80EwgGNkALk6c5C1EtWgAsqOi1QAb06groEbjWg8vVHOKcAvpokshy3vEgyyMr8kEbQJogAFND2YREAlOaW1soBeJAoAHSIkMTRmbbI8e6aPMiZxJmgACqCGKhY6ABGyDnkFFQ0dIzMbBwCwqIccabcYLyQoKjIEmh8kwN8DLAc5PzwwbLMyAAeK77IACYaQSEjUWZWhfYAjABMAMwALA+gbsVjoADqgjKESytQPxCHghAByXigYgBfr8LAsYj8aQMUASbDQcRSExCeCwFiIQh+AKfAYyBiQFgOPyIaikSGLQo0Zj-aazaY+dSaXjLDgAGXgAC9CKhDqAALxJaw2Ib2RzOISuDycLw+ImBYKQflCkWRRD2LXCw6JCxS1JCdJZHJ5RAFIbFJU8ADKC3WzEcnVZaGYE1ABpFnFOmsFhsil2uoHuzwArO9SmAAEIsSFrZB-GgAjjA5gtVN8VCEc1o1C4Q4AGlR2AwO1EsBQoAAbvB-gJ4HhPgB5aDwem-Ph1TCV3AEEirTp4ELtRbTPD4vwKjOfAuioSQHuDXBcnmgACC+eCONFEs73YAPGGZVT5cRyyhiHh7AAON7lsG3vBggB8XGV3l8-nVISOgghxoLq9i7io-AHsayRWGaFrlFauq2rg9qaIGQHwCBqChtKdgRo8TxRjeyB3o+7xAA), sometimes in place of the equivalent anonymous type (which may or may not be desirable). Interfaces will always be named in error messages.
> * Type aliases may not participate [in declaration merging, but interfaces can](https://www.typescriptlang.org/play?#code/PTAEEEDtQS0gXApgJwGYEMDGjSfdAIx2UQFoB7AB0UkQBMAoEUfO0Wgd1ADd0AbAK6IAzizp16ALgYM4SNFhwBZdAFtV-UAG8GoPaADmNAcMmhh8ZHAMMAvjLkoM2UCvWad+0ARL0A-GYWVpA29gyY5JAWLJAwGnxmbvGgALzauvpGkCZmAEQAjABMAMwALLkANBl6zABi6DB8okR4Jjg+iPSgABboovDk3jjo5pbW1d6+dGb5djLwAJ7UoABKiJTwjThpnpnGpqPBoTLMAJrkArj4kOTwYmycPOhW6AR8IrDQ8N04wmo4HHQCwYi2Waw2W1S6S8HX8gTGITsQA).
> * Interfaces may only be used to [declare the shapes of objects, not rename primitives](https://www.typescriptlang.org/play?#code/PTAEAkFMCdIcgM6gC4HcD2pIA8CGBbABwBtIl0AzUAKBFAFcEBLAOwHMUBPQs0XFgCahWyGBVwBjMrTDJMAshOhMARpD4tQ6FQCtIE5DWoixk9QEEWAeV37kARlABvaqDegAbrmL1IALlAEZGV2agBfampkbgtrWwMAJlAAXmdXdy8ff0Dg1jZwyLoAVWZ2Lh5QVHUJflAlSFxROsY5fFAWAmk6CnRoLGwmILzQQmV8JmQmDzI-SOiKgGV+CaYAL0gBBdyy1KCQ-Pn1AFFplgA5enw1PtSWS+vCsAAVAAtB4QQWOEMKBuYVUiVCYvYQsUTQcRSBDGMGmKSgAAa-VEgiQe2GLgKQA).
> * Interface names will [always appear in their original form](https://www.typescriptlang.org/play?#code/PTAEGEHsFsAcEsA2BTATqNrLusgzngIYDm+oA7koqIYuYQJ56gCueyoAUCKAC4AWHAHaFcoSADMaQ0PCG80EwgGNkALk6c5C1EtWgAsqOi1QAb06groEbjWg8vVHOKcAvpokshy3vEgyyMr8kEbQJogAFND2YREAlOaW1soBeJAoAHSIkMTRmbbI8e6aPMiZxJmgACqCGKhY6ABGyDnkFFQ0dIzMbBwCwqIccabcYLyQoKjIEmh8kwN8DLAc5PzwwbLMyAAeK77IACYaQSEjUWY2Q-YAjABMAMwALA+gbsVjNXW8yxySoAADaAA0CCaZbPh1XYqXgOIY0ZgmcK0AA0nyaLFhhGY8F4AHJmEJILCWsgZId4NNfIgGFdcIcUTVfgBlZTOWC8T7kAJ42G4eT+GS42QyRaYbCgXAEEguTzeXyCjDBSAAQSE8Ai0Xsl0K9kcziExDeiQs1lAqSE6SyOTy0AKQ2KHk4p1V6s1OuuoHuzwArMagA) in error messages, but only when they are used by name.
> 
> For the most part, you can choose based on personal preference, and TypeScript will tell you if it needs something to be the other kind of declaration. If you would like a heuristic, use interface until you need to use features from type.

**Comment by henryboldi** [comment]
I'm also under the impression that `interface` plays nicer with objects. How about we consistently use `interface` instead of `type` across the codebase?

**Comment by 0xDaedalus** [comment]
cc @Shadowfiend

**Comment by Shadowfiend** [comment]
Hey, sorry folks for missing the initial comments here. We've deliberately and intentionally been *preferring* `type` over `interface`. @beemeeupnow's quote from the docs covers exactly why:

> - Prior to TypeScript version 4.2

(We're on 4.3, need to actually bump up to latest sometime soon.)

> - Type aliases may not participate in declaration merging, but interfaces can

This is a vote in favor of type aliases, as by default we *do not want* declaration merging, since it introduces implicit behaviors. The Tally codebase should prefer explicit (in this case, explicitly merging two types using `&` into a new type with a different name) over implicit (implicitly merging new functionality into another imported interface with the same name) behaviors. If we do need it in a particular use case (typically when augmenting global objects in .d.ts files), we can use `interface` and deliberately and intentionally opt in to that behavior.

Incidentally, declaration merging is particularly dangerous for our current UI code because we generally declare our props types as simply `Props`. This means that if we ever export that `Props` type and import it somewhere else for some use, we can silently and unexpectedly broaden the accepted props for another component, since the matching name won't produce an error but will instead merge the interfaces.

> Interfaces may only be used to declare the shapes of objects, not rename primitives.

We deliberately do this type of renaming right now as a nominal type signal, and in preparation/hope that nominal types (see https://github.com/microsoft/TypeScript/issues/202) will be implemented and we'll have a codebase ready to work with them at that point. This also makes the need to use particular subsets of primitive types explicit (by stating the intended structure of the type) instead of implicit.

> Interface names will always appear in their original form.

This turns out to make understanding harder when trying to work with new code; here's an example pair of screenshots from when this was discussed internally by the dev team in August:

Hinting for `interface`:
<img width="434" alt="Screen Shot 2021-08-26 at 14 54 27" src="https://user-images.githubusercontent.com/8245/171970570-d7d6558e-cdab-4d55-8878-1db1d95d296e.png">


Vs hinting for `type`:
<img width="350" alt="Screen Shot 2021-08-26 at 14 54 58" src="https://user-images.githubusercontent.com/8245/171970556-d3aa57d3-7677-4636-8f78-73585c54430c.png">

-------

I emphasized above that we *prefer* `type` over `interface`. The functionality brought to the table by `interface` is still useful when it's the right tool for the job. `interface` is a great choice for defining an interface in the classic OO sense, where we are defining mostly methods that a class is expected to implement; indeed, we use it for this purpose in the [base service types](https://github.com/tallycash/extension/blob/main/background/services/types.ts). `interface` is also a great tool when we *need* to use declaration merging, as when we want to extend a built-in or global object to indicate functionality we know exists but that isn't yet covered by core TypeScript types; we use it for this purpose in the [Ledger USB types](https://github.com/tallycash/extension/blob/main/ui/components/Ledger/usb.d.ts) and to add the [provider bridge's various fields to the `window` object](https://github.com/tallycash/extension/blob/main/env.d.ts#L36-L55).

We use `type` more frequently because we are almost never doing either of these things; instead, the vast majority of typing in our system is specifically meant to define data shape, and the remainder of the system is largely defined in terms of functions over data. This is also why there is heavy use of type unions and intersections, which can in turn be [narrowed](https://www.typescriptlang.org/docs/handbook/2/narrowing.html#discriminated-unions). We could define the types that feed these unions and intersections as `interface`s, but there's no real need to, and using `type` across the board helps to hint that all of these types are all meant to talk about data shape.

This is also why I'm torn on enabling the linter rule for this one. The valid use cases for `interface` have nothing hacky about them here, they're just a right-tool-right-job situation. In general, when we have linter rule exceptions, it should be either because external libraries force certain behaviors, or because of type system limitations. This won't always be the case, but it feels weird to flip on a linter rule we're already not following for good reasons, vs flipping one one that we're not following but for bad reasons.

The last point here is this one:

> I'm also under the impression that interface plays nicer with objects.

Interested in hearing more here if there's some specific examples. As far as I know, the differences noted above are all of the differences between interfaces and type aliases.

------

Last note here: this is one of a handful of high-level decisions/principles used throughout the code base that really need to be documented, similar to how the Keep team flags their [Go development guidelines](https://github.com/keep-network/keep-core/blob/main/docs-v1/development/go-guidelines.adoc).
