### ISSUE TITLE
Copy address from accounts list

### ISSUE THREAD

**Issue by jagodarybacka** [tallyhowallet/extension#1147]
### Discord Discussion Link

https://discord.com/channels/808358975287722045/875438141610270740/951120858842275851

### What would you like to be able to do?

As mentioned in comments of #593 - add possibility to copy address from accounts list. 

![image](https://user-images.githubusercontent.com/20949277/157847413-6434cca4-0537-47de-a5c2-bbb15132bffc.png)

**Comment by jagodarybacka** [comment]
@VladUXUI I think you should take a look at it and confirm that the tooltip design should be the same as in the top menu. I feel like it won't look so good in this case, maybe quick prototype before implementation?

**Comment by Shadowfiend** [comment]
I don't know that a tooltip is the move here fwiw. For this particular place we could also look at using the menu just added for address removal. This also reminds me of https://github.com/tallycash/extension/issues/649, which we haven't circled back to yet.

**Comment by VladUXUI** [comment]
hey @jagodarybacka let's hold of on this. As this requires a bit more consideration.
The fix for this particular discussion is the "copy from top menu" that you already implemented.

Happy to revisit this later, maybe by working on https://github.com/tallycash/extension/issues/649, but that is on my plate atm

**Comment by 0xDaedalus** [comment]
No longer an issue ✅
