### ISSUE TITLE
Homebrew install is not supported with nvm

### ISSUE THREAD

**Issue by puppycodes** [tallyhowallet/extension#1942]
nvm installation isn't homebrew supported, initially I opened a pr but I realized we should probably update the macos-setup.sh to something that isn't piping curl to bash?

https://github.com/nvm-sh/nvm#installing-and-updating

> Homebrew installation is not supported. If you have issues with homebrew-installed nvm, please brew uninstall it, and install it using the instructions below, before filing an issue.

**Comment by Shadowfiend** [comment]
Does it not work or is it just unsupported? The simplicity of brew trumps them not wanting to answer questions about it imo, unless we run into issues with it.

**Comment by puppycodes** [comment]
this is the part that concerned me after reading the docs? but yes it does work so perhaps its non-issue

> Homebrew makes zsh directories unsecure

> zsh compinit: insecure directories, run compaudit for list.
> Ignore insecure directories and continue [y] or abort compinit [n]? y
> Homebrew causes insecure directories like /usr/local/share/zsh/site-functions and /usr/local/share/zsh. This is not an nvm problem - it is a homebrew problem. Refer https://github.com/zsh-users/zsh-completions/issues/680 for some solutions related to the issue.

**Comment by Shadowfiend** [comment]
https://docs.brew.sh/Shell-Completion#configuring-completions-in-zsh seems to be the recommended path here. Overall torn as it's good to be default friendly to a macOS install in our install scripts though, and since zsh is the default now... 

But curl and go isn't really a strategy I enjoy, which is partly why I've leaned on homebrew so heavily in install scripts. 

Hmmm 🤔

**Comment by puppycodes** [comment]
One thing i've considered as an alternative to solving the reproducibility vs repeatability problem is https://nixos.org. I love the idea, feels like the right balance between containerization and reliable cross platform builds https://nixos.org/guides/towards-reproducibility-pinning-nixpkgs.html#pinning-nixpkgs

**Comment by tallysam** [comment]
Why wouldn't we simply remove the broken brew command and install nvm the recommended way?

**Comment by Shadowfiend** [comment]
The answer, btw, is because curl-and-pipe is how you get pwned, and ideally you should do it when you know you're doing it as opposed to hidden behind an install script. 

If we want to use nvm and install it this way, I suggest making the install script stop and warn the user it's about to pipe the specific URL on over.

**Comment by tallysam** [comment]
I agree that curl and bash is how you get owned. We don't want to take that kind of responsibility.

I suggest the following:

  1. A check in the install script for a valid nvm. If it fails then we bail out and point the user to the nvm instructions with our added security warnings.
  2. Update the README under the quick-start section. Place a similar piece of text about the nvm requirement and subsequent security warnings about curl-bash type installs.
