### ISSUE TITLE
Fallback to block events when we can't use `alchemy_getAssetTransfers`

### ISSUE THREAD

**Issue by mhluongo** [tallyhowallet/extension#2192]
In order to stop relying on `alchemy_getAssetTransfers`, we will eventually need to actually poll-for and index each block.  This will likely result in too much disk I/O as we support more chains with shorter block times (BSC comes to mind) so we will probably need to rethink some of the architecture around this.  Batching writes to disk could go a long way here.

_Originally posted by @0xDaedalus in https://github.com/tallycash/extension/issues/2189#issuecomment-1247266833_

**Comment by greg-nagy** [comment]
We will probably need to think more about the approach here, because our limitations as a client side extension will limit what and how we can deal with. 

Storing every block won't be a sufficient strategy here for indexing purposes, because the size won't fit on the users machine. If we store only the logs it's still ~4 gb per year only on mainnet. 

I might have found a workaround though. I think we can outsource this responsibility to the RPC nodes in a provider agnostic way.  If we create a filter for the events that we care about, we can register this in the RPC node and there is a polling api for the given filter. With this — if works as I think it works — we can get to a point where our polling is really cheap, and we need to start looking up txs when there was activity and store only those. This would take us from `address` * `network` * `time` > `address` * `network` * `activity`

eth_newFilter
https://docs.alchemy.com/reference/eth-newfilter

eth_getFilterChanges
https://docs.alchemy.com/reference/eth-getfilterchanges

**Comment by 0xDaedalus** [comment]
Not on the roadmap for the near future
