### ISSUE TITLE
Sign in with Ethereum fails if Optimism network is selected in the wallet.

### ISSUE THREAD

**Issue by 0xDaedalus** [tallyhowallet/extension#2361]
### To Recreate
- Select `Optimism` via the in-wallet network switcher
- Navigate to https://login.xyz/
- Attempt to sign in in the `Try it out` section.

**Comment by Shadowfiend** [comment]
This *appears* not to be our fault. In particular, it seems to be happening due to an attempted ENS lookup by the SIWE page, which is failing in Ethers due to Optimism being unsupported for ENS lookups in the version of Ethers they're using. It seems to also block Metamask from attempting a signature. It appears to happen on Polygon as well.
