### ISSUE TITLE
Review and fix UI issues with long address names

### ISSUE THREAD

**Issue by jagodarybacka** [tallyhowallet/extension#2410]
If user has long name (UNS/ENS) it can be a problem in the UI. Let's find broke places ad fix them with elipsis and browser tooltip (title attribute)
![image](https://user-images.githubusercontent.com/20949277/195118167-e8d7afb3-0e69-4098-be7b-9bc074d737ea.png)
![image](https://user-images.githubusercontent.com/20949277/195118206-79ab186a-f627-4b52-a029-cafc3b37002c.png)

**Comment by diegoalzate** [comment]
Hey I think I can do this

**Comment by jagodarybacka** [comment]
@diegoalzate yes please it's all yours 😄

**Comment by kkosiorowska** [comment]
The issue is no longer there :white_check_mark:

![Screenshot 2022-12-30 at 15 28 51](https://user-images.githubusercontent.com/23117945/210081027-c2033d37-8c63-407e-86ec-ff982289d889.png)

![Screenshot 2022-12-30 at 15 28 35](https://user-images.githubusercontent.com/23117945/210081042-2dca43cb-81f3-469a-b4c3-72532997d479.png)
