### ISSUE TITLE
tx-error: 'the user rejected the request'

### ISSUE THREAD

**Issue by Naxsun** [tallyhowallet/extension#2672]
### Discord Discussion Link

na

### What browsers are you seeing the problem on?

Chrome

### What were you trying to do?

Set-up a transaction

### What did not work?

Some users have reported receiving an error message when setting up a transaction. "The user rejected the request". 

It seems to not be user specific, but apply to all users for affect dApps, or transaction types on a specific dApp. With some dapps it consistently fails the 1st time, but when a user repeats tx set-up it does succeed.

There could be a relation with transactions that require an approval first, or where an approval tx is expected but approval was already given earlier on.

Reports / to reproduce:

**User: Nax**
**Swap on Velodrome (Optimism)**
Logs:
[logs_v0_18_2__2022-11-24T11_11_41+01_00.txt](https://github.com/tallycash/extension/files/10083365/logs_v0_18_2__2022-11-24T11_11_41%2B01_00.txt)

<img width="1386" alt="Screen Shot 2022-11-24 at 11 11 18" src="https://user-images.githubusercontent.com/71384922/203757407-8fe537ac-aa4c-4693-b943-198c85ca1058.png">

After receiving this error message, hit swap again, and it'll go through
<img width="893" alt="Screen Shot 2022-11-24 at 11 12 28" src="https://user-images.githubusercontent.com/71384922/203758145-f493eff9-2755-4ad9-b5c7-805de53c9a90.png">

**User: KrasniyVladi | Sui Global#3627**
**Bridge on https://app.chainhop.exchange/**

"
sup guys, cant make bridge with chainhop from optimism to arbitrum. I click to sign the transaction and nothing happens. I updated the site, reconnected - nothing works.
[2022-11-19 18:34:33.360][log][main.6855edfc.chunk.js:1 ()]  err: {code: 4001, message: 'The user rejected the request.'}
"
Logs:
[logs_v0_18_0__2022-11-19T18_39_3803_00 (2).txt](https://github.com/tallycash/extension/files/10083429/logs_v0_18_0__2022-11-19T18_39_3803_00.2.txt)

Note Nax: User used 0.18.0, I've failed to reproduce it with 0.18.2

### Version

v0.18.2

**Comment by Naxsun** [comment]
There's also been users that reported the same error message for specific bridge&swap actions on Bungee. E.g. bridge USDC on Optimism to DAI on Arbitrum. 

This is however not consistent. Since Bungee is an aggregator, it could be specific to the actual bridge routing & tx.

**Comment by greg-nagy** [comment]
The user rejected is the default error message that we send back to the dApp if ANYTHING goes wrong. 
[see `ProviderBridgeService`](https://github.com/tallycash/extension/blob/b87b86ab260825eec97ded7d8832378d8cbe63d0/background/services/provider-bridge/index.ts#L244-L250)

The scope of this issue should be to 
- change this behavior for allowing the actual error message to propagate to the user 
- check what causes the issue on velodrome — that site is prone for having this problem 
- try to fix it

With this allowing normal error propagation back to the dApp is a huge improvement because in the future we can pinpoint better what went wrong

**Comment by puppycodes** [comment]
Wont Fix: **Could not reproduce**

**Comment by Naxsun** [comment]
This was fixed. Don't know the PR but there was a fix
