### ISSUE TITLE
Transferring NFT has some strange results

### ISSUE THREAD

**Issue by VladUXUI** [tallyhowallet/extension#2896]
I transfered one of the NFT WORLD - OS (used to be 2) to another imported wallet
And it split up the collection into two different NFT's (collections)
![image](https://user-images.githubusercontent.com/80846886/213651246-ea18d44e-fde7-4611-af5b-0d901d0b2de9.png)

________________

Nothing was done, and couple of minutes later the newly transferred NFT vanished and it keeps loading. (even 10 min later)
![image](https://user-images.githubusercontent.com/80846886/213651375-da4543f5-1a28-4d34-8a70-27b12ce689e6.png)
**^^ This one was fixed with extension reloaded**

________________

There is only one NFT in this collection because one was moved. Number doesn't seem to update
![image](https://user-images.githubusercontent.com/80846886/213651414-6c60023f-a842-4d6a-a875-52978941b9c7.png)

**Comment by VladUXUI** [comment]
Interesting, after another refresh. NFT Words 0 OS(2) now has both NFTs in it. But they are both for the same owner.
And then there is a separate one that has the right owner

**Comment by jagodarybacka** [comment]
So apparently we had 2 Skywalk NFTs and only one was transferred so it is ok that they are "duplicated" in collections because they are in fact owned by two accounts. The vanished-and-loading NFT issue will be investigated.
![image](https://user-images.githubusercontent.com/20949277/213701607-400b491f-ccb3-4141-9dbd-b775e0d80178.png)
