### ISSUE TITLE
KEEP logo is super blurry / low-res

### ISSUE THREAD

**Issue by mr-michael** [tallyhowallet/extension#559]
### What browsers are you seeing the problem on?

Chrome

### What were you trying to do?

-

### What did not work?

Keep logo was SUPER blurry during first 10 mins after install throughout the app

<img width="114" alt="Screen Shot 2021-12-10 at 3 54 55 PM" src="https://user-images.githubusercontent.com/7005061/145643607-5eae8241-8991-4926-bfd3-57a1a2955f47.png">

<img width="372" alt="Screen Shot 2021-12-10 at 3 53 33 PM" src="https://user-images.githubusercontent.com/7005061/145643624-90e07528-6a91-4226-a1e1-88a65c13c48e.png">

(ETH logo looks fine though)

<img width="165" alt="Screen Shot 2021-12-10 at 3 54 37 PM" src="https://user-images.githubusercontent.com/7005061/145643661-561cca6b-a333-44fa-b2d8-21fb579df89b.png">

When I checked back about 30 mins later it looked fine though:

<img width="454" alt="Screen Shot 2021-12-10 at 4 29 34 PM" src="https://user-images.githubusercontent.com/7005061/145643836-d674d0f7-60cf-4607-892b-53f08e0018eb.png">

**Comment by mhluongo** [comment]
I think these are the logos from Alchemy rather than the token lists. Eg ENS looks similarly off and it's not in any of the token lists at all

![Screenshot from 2021-12-14 20-30-43](https://user-images.githubusercontent.com/427505/146106246-eb808d7b-1d1d-4b03-b5f3-260191733144.png)

**Comment by creckhow** [comment]
hmmm I've got a general question about where these token lists and logs are getting pulled from... because I'm never seeing a real USDC logo, just always getting a U: 

<img width="357" alt="Screen Shot 2021-12-14 at 9 02 46 PM" src="https://user-images.githubusercontent.com/74791142/146109420-72af9448-098d-4131-92f1-1bd93e877a3f.png">

And I pulled in a read only of an degen play wallet with small amounts of FXS, TRIBE, ALCX, LQTY in it (above $5 worth for each one) -- none of which showed up. Is that known? If yes, what token metadata list are we using for CE and why does it suck?

**Comment by mhluongo** [comment]
LOL I know exactly what that play wallet is farming!

For USDC, this is the same Alchemy issue I'm trying to figure out. The token list metadata is getting overridden.

For the DeFi tokens.... I believe the token lists are generally excellent, but might need updating. This could also be the same issue though.

[Here are the JSON URLs](https://github.com/tallycash/extension/blob/04dd8068a603021e90683fdb0219cd357aa7ef9b/background/services/preferences/defaults.ts#L7). If you want to spot check them or find others that do a better job with mid-cap DeFi, I'd welcome the help @creckhow

**Comment by 0xDaedalus** [comment]
This is no longer an issue ✅
