### ISSUE TITLE
EtherScan asset parity

### ISSUE THREAD

**Issue by mr-michael** [tallyhowallet/extension#590]
### What browsers are you seeing the problem on?

Chrome

### What were you trying to do?

Check my Tally portfolio balance against same on etherscan

### What did not work?

Tally balance is indeed a bit lower - presumbly b/c some tokens either haven't tricked in or won't trickle in (this was 60+ mins) after loading read-only acct. think this is a 'so be it' situation but felt worth flagging.

https://etherscan.io/tokenholdings?a=0x00de4b13153673bcae2616b67bf822500d325fc3

<img width="1263" alt="Screen Shot 2021-12-11 at 6 19 02 PM" src="https://user-images.githubusercontent.com/7005061/145694655-1826328e-946b-42aa-ab4e-aaf2c4ab22da.png">

**Comment by mhluongo** [comment]
Catching up with the fidelity EtherScan while looking more like Zapper/Zerion is the aspiration. It's going to be a few sprints if we want it though

**Comment by mhluongo** [comment]
Switched this to a feature request. There might be some bugs underlying the disparity, but we'd need way more detail on which assets if that's the case. Otherwise I think "moar coverage" is what we want... eg balance checking all tokens in our token lists rather than just using the default Alchemy check.

**Comment by 0xDaedalus** [comment]
This seems to no longer be the case - especially with the change we've made to balance & price fetching since 12/21
